package com.matlasystems.chat.common.event;
/** Types of domain events emitted by the chat platform. */
public enum EventType {
    USER_CONNECTED, USER_DISCONNECTED, USER_LOGGED_IN, USER_LOGGED_OUT, USER_REGISTERED,
    MESSAGE_SENT, MESSAGE_DELIVERED, BROADCAST_MESSAGE, PRIVATE_MESSAGE,
    FILE_UPLOAD_STARTED, FILE_UPLOAD_COMPLETED, FILE_DOWNLOAD_STARTED, FILE_DOWNLOAD_COMPLETED,
    SERVER_STARTED, SERVER_STOPPED, CLIENT_CONNECTED, CLIENT_DISCONNECTED,
    SESSION_CREATED, SESSION_EXPIRED, SESSION_DESTROYED
}
