package com.matlasystems.chat.common.enums;

/**
 * Represents the supported message types
 * within the chat platform.
 *
 * @author MATLA Systems
 * @version 1.0.0
 */
public enum MessageType {

    /**
     * Direct message between two users.
     */
    PRIVATE,

    /**
     * Message sent to every connected user.
     */
    BROADCAST,

    /**
     * System-generated message.
     */
    SYSTEM,

    /**
     * Message containing a file transfer.
     */
    FILE;

    /**
     * Determines whether the message
     * targets a single user.
     *
     * @return true if private
     */
    public boolean isPrivate() {
        return this == PRIVATE;
    }

    /**
     * Determines whether the message
     * targets every connected user.
     *
     * @return true if broadcast
     */
    public boolean isBroadcast() {
        return this == BROADCAST;
    }

    /**
     * Determines whether the message
     * was generated by the server.
     *
     * @return true if system message
     */
    public boolean isSystem() {
        return this == SYSTEM;
    }

    /**
     * Determines whether this message
     * represents a file transfer.
     *
     * @return true if file message
     */
    public boolean isFile() {
        return this == FILE;
    }

}
